#server
server:
  port: 8484

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CodaeSeong/springconfig
          default-label: main
          search-paths: /**

